<?php
require_once __DIR__.'/config.php';
$where=['is_active = 1'];$params=[];
foreach(['category','color','brand'] as $field){if(!empty($_GET[$field])){$where[]="$field = :$field";$params[$field]=$_GET[$field];}}
if(!empty($_GET['type'])){$where[]='product_type = :type';$params['type']=$_GET['type'];}
if(!empty($_GET['size'])){$where[]='FIND_IN_SET(:size, sizes)';$params['size']=$_GET['size'];}
if(!empty($_GET['q'])){$where[]='(name LIKE :q OR brand LIKE :q)';$params['q']='%'.$_GET['q'].'%';}
$sort=($_GET['sort']??'')==='high'?'price DESC':(($_GET['sort']??'')==='low'?'price ASC':'created_at DESC');$stmt=db()->prepare('SELECT * FROM products WHERE '.implode(' AND ',$where)." ORDER BY $sort");$stmt->execute($params);$products=$stmt->fetchAll();$colors=db()->query('SELECT DISTINCT color FROM products WHERE is_active=1 ORDER BY color')->fetchAll(PDO::FETCH_COLUMN);$brands=db()->query('SELECT DISTINCT brand FROM products WHERE is_active=1 ORDER BY brand')->fetchAll(PDO::FETCH_COLUMN);$page_title='Mellow Wear | เสื้อผ้าทุกวัน';require __DIR__.'/partials_header.php';
?>
<main class="storefront" id="top">
<section class="store-hero" data-reveal><div class="hero-slide active"><img src="https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1800&q=88" alt="คอลเลกชันเสื้อผ้า Mellow Wear"><div class="hero-overlay"></div><div class="hero-copy"><div class="eyebrow">THE NEW EVERYDAY</div><h1>แต่งตัวให้<br><em>สบายในแบบคุณ</em></h1><p>คอลเลกชันใหม่ที่ออกแบบให้ทุกวันดูดี<br>และเคลื่อนไหวได้อย่างเป็นธรรมชาติ</p><a class="button hero-button" href="#new-arrivals">สำรวจคอลเลกชัน <span>↗</span></a></div></div><div class="hero-slide slide-alt"><img src="https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1800&q=88" alt="เสื้อผ้าคอลเลกชันผู้หญิง"><div class="hero-overlay"></div><div class="hero-copy"><div class="eyebrow">SOFT SILHOUETTES</div><h1>เรียบง่าย<br><em>แต่มีความหมาย</em></h1><p>โทนสีที่หยิบมาใส่ได้ทุกฤดูกาล<br>สำหรับสไตล์ของคุณ</p><a class="button hero-button" href="index.php?category=women">ดูผู้หญิง <span>↗</span></a></div></div><button class="hero-arrow prev" aria-label="สไลด์ก่อนหน้า">←</button><button class="hero-arrow next" aria-label="สไลด์ถัดไป">→</button><div class="hero-dots"><i class="active"></i><i></i><i></i></div><div class="hero-label">MELLOW<br><b>WEAR</b></div></section>
<section class="service-row" data-reveal><div><span>✦</span><b>EVERYDAY ESSENTIALS</b><small>ชิ้นโปรดที่ใส่ได้บ่อย</small></div><div><span>↺</span><b>14 DAYS RETURN</b><small>เปลี่ยนใจได้ภายใน 14 วัน</small></div><div><span>⌁</span><b>READY TO SHIP</b><small>จัดส่งรวดเร็วทั่วประเทศ</small></div><div><span>♡</span><b>MELLOW MEMBER</b><small>สิทธิพิเศษสำหรับสมาชิก</small></div></section>
<section class="shop-categories section-shell" data-reveal><div class="section-intro"><div><div class="eyebrow">SHOP BY MOOD</div><h2>เลือกสไตล์ของคุณ</h2></div><a class="view-link" href="#filters">ดูทั้งหมด →</a></div><div class="category-editorial"><a class="cat-tile cat-men" href="index.php?category=men"><img src="https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=900&q=85" alt="เสื้อผ้าผู้ชาย" loading="lazy"><span>01</span><div><b>ผู้ชาย</b><small>Quiet confidence</small></div><i>↗</i></a><a class="cat-tile cat-women" href="index.php?category=women"><img src="https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=85" alt="เสื้อผ้าผู้หญิง" loading="lazy"><span>02</span><div><b>ผู้หญิง</b><small>Softly considered</small></div><i>↗</i></a><a class="cat-tile cat-kids" href="index.php?category=kids"><img src="https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=900&q=85" alt="เสื้อผ้าเด็ก" loading="lazy"><span>03</span><div><b>เด็ก</b><small>Made to move</small></div><i>↗</i></a></div></section>
<section class="promo-banner section-shell" data-reveal><div class="promo-image"><img src="https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1400&q=85" alt="Mellow Wear new collection" loading="lazy"></div><div class="promo-copy"><div class="eyebrow">MELLOW EDIT / 01</div><h2>Less noise.<br><em>More you.</em></h2><p>เสื้อผ้าที่ปล่อยให้คุณเป็นตัวเองได้เต็มที่ ผ่านรูปทรงและเนื้อผ้าที่คิดมาอย่างดี</p><a class="text-link" href="#new-arrivals">ค้นหาชิ้นโปรดของคุณ ↗</a></div></section>
<section class="store-products section-shell" id="new-arrivals"><div class="section-intro" data-reveal><div><div class="eyebrow">CURATED FOR YOU</div><h2>สินค้าใหม่ล่าสุด</h2></div><a class="view-link" href="#filters">ดูทั้งหมด →</a></div><div class="product-grid store-grid"><?php foreach($products as $i=>$p): $cardSizes=array_values(array_filter(array_map('trim',preg_split('/[,|]/',(string)($p['sizes']??''))))); ?><article class="card store-card" data-reveal style="--delay:<?=$i*70?>ms"><a class="card-image" href="product.php?id=<?=$p['id']?>"><img src="<?=e($p['image_url'])?>" alt="<?=e($p['name'])?>" loading="lazy"><span class="card-badge">NEW</span><span class="view-product">ดูรายละเอียด <b>→</b></span></a><div class="card-body"><div class="card-meta"><?=e($p['brand'])?> · <?=['men'=>'ผู้ชาย','women'=>'ผู้หญิง','kids'=>'เด็ก'][$p['category']]?></div><h3><?=e($p['name'])?></h3><div class="card-bottom"><div class="price">฿<?=number_format((float)$p['price'])?></div><span class="stock-dot" title="พร้อมส่ง"></span></div></div><form method="post" action="cart.php" class="quick-add-form"><input type="hidden" name="action" value="add"><input type="hidden" name="product_id" value="<?=$p['id']?>"><input type="hidden" name="color" value="<?=e($p['color'])?>"><input type="hidden" name="size" value="<?=e($cardSizes[0]??'')?>"><input type="hidden" name="quantity" value="1"><input type="hidden" name="return_to" value="cart.php"><button class="button" type="submit">เพิ่มลงตะกร้า</button></form></article><?php endforeach; if(!$products): ?><p class="muted">ยังไม่พบสินค้าที่ตรงกับตัวกรอง</p><?php endif ?></div></section>
<section class="filter-section section-shell" id="filters" data-reveal><div class="filter-heading"><div class="eyebrow">FIND YOUR FIT</div><h2>ค้นหาชิ้นที่ใช่</h2><p>เลือกจากหมวดหมู่ สี ไซซ์ หรือแบรนด์ที่คุณชอบ</p></div><form class="filters store-filters" method="get"><input name="q" value="<?=e($_GET['q']??'')?>" placeholder="ค้นหาสินค้า หรือแบรนด์"><select name="category"><option value="">ทุกหมวดหมู่</option><?php foreach(['men'=>'ผู้ชาย','women'=>'ผู้หญิง','kids'=>'เด็ก'] as $v=>$label):?><option value="<?=$v?>" <?=($_GET['category']??'')===$v?'selected':''?>><?=$label?></option><?php endforeach?></select><select name="size"><option value="">ทุกไซซ์</option><?php foreach(['S','M','L','XL','100','110','120','130','30','32','34','36'] as $v):?><option <?=($_GET['size']??'')===$v?'selected':''?>><?=$v?></option><?php endforeach?></select><select name="color"><option value="">ทุกสี</option><?php foreach($colors as $v):?><option <?=($_GET['color']??'')===$v?'selected':''?>><?=e($v)?></option><?php endforeach?></select><select name="brand"><option value="">ทุกแบรนด์</option><?php foreach($brands as $v):?><option <?=($_GET['brand']??'')===$v?'selected':''?>><?=e($v)?></option><?php endforeach?></select><select name="sort"><option value="">สินค้าใหม่</option><option value="high" <?=($_GET['sort']??'')==='high'?'selected':''?>>ราคาสูงไปต่ำ</option><option value="low" <?=($_GET['sort']??'')==='low'?'selected':''?>>ราคาต่ำไปสูง</option></select><button class="button">ค้นหา <span>→</span></button></form></section>
<section class="editorial-video section-shell" data-reveal><div class="editorial-media"><img src="https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1800&q=85" alt="Mellow Wear editorial" loading="lazy"><div class="media-shade"></div><div class="play-button" role="button" aria-label="เล่นวิดีโอ">▶</div><span class="media-caption">MELLOW STORIES / 01</span></div><div class="editorial-copy"><div class="eyebrow">THE MELLOW JOURNAL</div><h2>แต่งตัวดี<br>ในวันที่เป็นคุณ</h2><p>เรื่องราวของผ้า ผู้คน และรายละเอียดเล็ก ๆ ที่ทำให้เสื้อผ้าหนึ่งตัวอยู่กับคุณได้นานขึ้น</p><a class="text-link" href="index.php#new-arrivals">อ่านเรื่องราวของเรา ↗</a></div></section>
<section class="social-gallery section-shell" data-reveal><div class="section-intro centered"><div><div class="eyebrow">#MELLOWINMOTION</div><h2>สไตล์จากคนของเรา</h2></div><span class="muted">แชร์ลุคของคุณกับเรา</span></div><div class="gallery-grid"><img src="https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=700&q=80" alt="Mellow community style" loading="lazy"><img src="https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=700&q=80" alt="Mellow community style" loading="lazy"><img src="https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=700&q=80" alt="Mellow community style" loading="lazy"><img src="https://images.unsplash.com/photo-1506629905607-d9b1bdbf9c27?auto=format&fit=crop&w=700&q=80" alt="Mellow community style" loading="lazy"><img src="https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=700&q=80" alt="Mellow community style" loading="lazy"></div></section>
</main><?php require __DIR__.'/partials_footer.php'; ?>
