<?php
require_once __DIR__.'/config.php';
if (current_user()) redirect('member.php');
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (empty($_POST['consent'])) { flash('error', 'กรุณายอมรับข้อกำหนดการใช้งานและนโยบายความเป็นส่วนตัวก่อนสมัครสมาชิก'); }
    else {
    $name = trim($_POST['name'] ?? ''); $email = strtolower(trim($_POST['email'] ?? ''));
    $phone = preg_replace('/[^0-9+\-\s()]/', '', trim($_POST['phone'] ?? '')); $pass = $_POST['password'] ?? ''; $confirm = $_POST['confirm_password'] ?? '';
    if (mb_strlen($name) < 2 || !filter_var($email, FILTER_VALIDATE_EMAIL) || strlen(preg_replace('/\D/', '', $phone)) < 9 || strlen($pass) < 8) flash('error', 'กรุณากรอกชื่อ อีเมล เบอร์โทร และรหัสผ่านอย่างน้อย 8 ตัวอักษรให้ครบ');
    elseif ($pass !== $confirm) flash('error', 'รหัสผ่านและการยืนยันรหัสผ่านไม่ตรงกัน');
    else { try { $s = db()->prepare('INSERT INTO users(name,email,phone,password_hash,is_verified) VALUES(?,?,?,?,1)'); $s->execute([$name, $email, $phone, password_hash($pass, PASSWORD_DEFAULT)]); $id = (int)db()->lastInsertId(); $_SESSION['user'] = ['id'=>$id,'name'=>$name,'email'=>$email,'role'=>'member']; flash('success', 'สร้างบัญชีสำเร็จ ยินดีต้อนรับสู่ '.STORE_NAME); redirect('index.php'); } catch (PDOException $e) { flash('error', 'อีเมลนี้ถูกใช้งานแล้ว'); } }
    }
}
$page_title = 'สมัครสมาชิก | '.STORE_NAME; require __DIR__.'/partials_header.php';
?>
<main class="auth-wrap auth-experience"><aside class="auth-showcase"><div class="showcase-copy"><div class="eyebrow">MELLOW WEAR MEMBERS</div><h2>พื้นที่เล็ก ๆ<br>สำหรับสไตล์<br>ที่เป็นคุณ</h2><p>เป็นสมาชิกเพื่อรับข่าวคอลเลกชันใหม่ก่อนใคร และจัดการทุกการเลือกของคุณได้ง่ายขึ้น</p></div><div class="showcase-note"><span>01 / MEMBER</span><b>Made for your<br>everyday.</b></div></aside><section class="auth-card auth-card-wide"><div class="auth-heading"><div class="auth-kicker"><span class="step-badge">01</span> CREATE ACCOUNT</div><h1>สร้างบัญชีใหม่</h1><p>ใช้เวลาเพียงครู่เดียว แล้วเริ่มเลือกสิ่งที่ใช่สำหรับคุณ</p></div><form method="post" class="form-stack" data-register-form novalidate><div class="field"><label for="name">ชื่อที่แสดง</label><div class="input-wrap"><span>◌</span><input id="name" name="name" autocomplete="name" placeholder="เช่น มินตรา" required></div></div><div class="form-row"><div class="field"><label for="email">อีเมล</label><div class="input-wrap"><span>✉</span><input id="email" name="email" type="email" autocomplete="email" placeholder="you@email.com" required></div></div><div class="field"><label for="phone">เบอร์โทรศัพท์</label><div class="input-wrap"><span>⌕</span><input id="phone" name="phone" type="tel" inputmode="tel" autocomplete="tel" placeholder="08x-xxx-xxxx" required></div></div></div><div class="field"><label for="password">รหัสผ่าน</label><div class="input-wrap password-wrap"><span>⌁</span><input id="password" name="password" type="password" autocomplete="new-password" placeholder="อย่างน้อย 8 ตัวอักษร" minlength="8" required><button class="password-toggle" type="button" aria-label="แสดงรหัสผ่าน">แสดง</button></div><div class="password-meter" aria-hidden="true"><i></i><i></i><i></i><i></i></div><small class="field-hint">ใช้ตัวอักษร ตัวเลข และสัญลักษณ์เพื่อความปลอดภัย</small></div><div class="field"><label for="confirm_password">ยืนยันรหัสผ่าน</label><div class="input-wrap password-wrap"><span>⌁</span><input id="confirm_password" name="confirm_password" type="password" autocomplete="new-password" placeholder="กรอกรหัสผ่านอีกครั้ง" minlength="8" required><button class="password-toggle" type="button" aria-label="แสดงรหัสผ่าน">แสดง</button></div><small class="match-message" aria-live="polite"></small></div><label class="consent"><input type="checkbox" required><span>ฉันยอมรับ <a href="#">ข้อกำหนดการใช้งาน</a> และ <a href="#">นโยบายความเป็นส่วนตัว</a></span></label><button class="button full submit-button"><span>สร้างบัญชีของฉัน</span><b>→</b></button></form><div class="divider"><span>หรือสมัครอย่างรวดเร็ว</span></div><div class="social"><a href="auth/google_start.php"><b class="google-mark">G</b> สมัครด้วย Google</a><a href="#" onclick="alert('Facebook OAuth ต้องตั้งค่า App ID ก่อน');return false"><b class="facebook-mark">f</b> สมัครด้วย Facebook</a></div><p class="fine">มีบัญชีแล้ว? <a href="login.php">เข้าสู่ระบบ</a></p></section></main><?php require __DIR__.'/partials_footer.php'; ?>
