<?php
require_once __DIR__.'/config.php';
if (!current_user()) { flash('error','กรุณาเข้าสู่ระบบเพื่อใช้รายการโปรด'); redirect('login.php'); }
$id=(int)($_POST['product_id']??$_GET['product_id']??0);
if ($_SERVER['REQUEST_METHOD']==='POST' && !verify_csrf($_POST['csrf']??null)) { http_response_code(403); exit('คำขอไม่ถูกต้อง'); }
if ($id) { $exists=db()->prepare('SELECT 1 FROM wishlists WHERE user_id=? AND product_id=?'); $exists->execute([current_user()['id'],$id]); if($exists->fetchColumn()) db()->prepare('DELETE FROM wishlists WHERE user_id=? AND product_id=?')->execute([current_user()['id'],$id]); else db()->prepare('INSERT IGNORE INTO wishlists(user_id,product_id) VALUES(?,?)')->execute([current_user()['id'],$id]); }
if ($_SERVER['REQUEST_METHOD']==='POST') { flash('success','อัปเดตรายการโปรดแล้ว'); redirect($_POST['return_to']??'wishlist.php'); }
$s=db()->prepare('SELECT p.* FROM wishlists w JOIN products p ON p.id=w.product_id WHERE w.user_id=? ORDER BY w.created_at DESC'); $s->execute([current_user()['id']]); $products=$s->fetchAll(); $page_title='รายการโปรด | '.STORE_NAME; require __DIR__.'/partials_header.php';
?><main class="container"><section class="panel"><div class="eyebrow">SAVED FOR LATER</div><h1>รายการโปรด</h1><div class="product-grid"><?php foreach($products as $p): ?><article class="card"><a class="card-image" href="product.php?id=<?=$p['id']?>"><img src="<?=e($p['image_url'])?>" alt="<?=e($p['name'])?>"></a><div class="card-body"><div class="card-meta"><?=e($p['brand'])?></div><h3><?=e($p['name'])?></h3><div class="price">฿<?=number_format($p['price'],2)?></div><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="product_id" value="<?=$p['id']?>"><button class="text-button danger-text">นำออกจากรายการโปรด</button></form></div></article><?php endforeach; ?></div><?php if(!$products): ?><p class="muted">ยังไม่มีรายการโปรด</p><?php endif; ?></section></main><?php require __DIR__.'/partials_footer.php'; ?>
